### ISSUE TITLE
Readme falsely states that the default scope manager is thread-local

### ISSUE THREAD

**Issue by mihau** [opentracing/opentracing-python#98]
The readme states that the default scope manager is thread-local but the reality is that `ScopeManager` class is used. Either the readme should be changed or the code. IMHO changing the code would be better since using just `ScopeManager` isn't really useful.

**Comment by carlosalberto** [comment]
Hey @mihau 

You are referring to this part?

> There exist implementations for thread-local (the default)

In this case, the idea was to say that `ThreadLocalScopeManager` is the default instance for this submodule (`opentracing.scope_managers`), not that it's the default for `Tracer` (we should update the README to clarify this, of course).

And we cannot use `ThreadLocalScopeManager` for `opentracing.Tracer` - this is because it's supposed to be a no-op implementation. However, `opentracing.mocktracer.MockTracer` does use `ThreadLocalScopeManager` as its default ;)

**Comment by mihau** [comment]
Yes that's the part I was referring to. Thanks a lot for clarifying, makes perfect sense now. With a slight change in the README it should be clear to anybody.
